name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04, macos-latest]
        cliffversion : [latest, "0.6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%W")"
        shell: bash

      - name: Setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.os }}-${{ steps.get-date.outputs.date }}-cargo-cliff-${{ matrix.cliffversion}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [[ "${{ matrix.cliffversion }}" == "latest" ]]; then
            cargo install git-cliff
          else
            cargo install --version ${{ matrix.cliffversion }} git-cliff
          fi

      - name: Setup git user with signing
        run: |
          git config --global user.email "djchentulmen@fia.org"
          git config --global user.name "Niki Lauda"
          gpg --batch --gen-key <<EOF                                                                                                                             2 ✘
            %no-protection
            Key-Type: 1
            Key-Length: 2048
            Subkey-Type: 1
            Subkey-Length: 2048
            Name-Real: Niki Lauda
            Name-Email: djchentulmen@fia.org
            Expire-Date: 0
            EOF
          git config --global user.signingkey $(gpg --list-secret-keys --keyid-format=long jh.ewers@gmail.com | grep 'sec' | awk 'match($0, /[0-9A-Z]{16}/) {print substr($0, RSTART, RLENGTH)}')

      - name: Create test environment
        run: |
          cd ..
          git clone git-release/ git-release-test
          cd git-release-test
          git remote rm origin
          cd ../git-release
          git remote rename origin origin-renamed
          git remote add origin ../git-release-test

          git switch -c rawe-ceek
          seq 100 > seq.txt
          git add seq.txt
          git commit seq.txt -m "feat: test-data"

      - name: Install git-release
        run: sudo make install

      - name: Run git-release
        run:  git release v90.90.90
